### ISSUE TITLE
Script ware Support

### ISSUE THREAD

**Issue by ege75753** [saucekid/sauceVR#14]
i have a script ware and i really like this script but its not working on script ware Saucekid please can you fix so it works on script ware too 

Thanks

**Comment by Gavinyboio69** [comment]
no.

**Comment by saucekid** [comment]
rostruct, the framework that saucevr was built on uses forward slashes to read files and scriptware does not support forward slashes

here is a quick fix made by someone in my discord, just put this before the loadstring

```lua
local _makefolder = makefolder
makefolder = function(str)
    local x = string.sub(str,string.len(str))
    if x == "/" then
        str = str:sub(1, -2)
    end
    return _makefolder(str)
end```

**Comment by ege75753** [comment]
still does not work i tried to execute the script u gave before and then executed the loadstring didnt work i put the script before the loadstring still no work
