### ISSUE TITLE
arms + legs disappearing

### ISSUE THREAD

**Issue by sanderabelsen** [saucekid/sauceVR#19]
i enter roblox execute the script see my arms and legs for 2 seconds and then they randomly disappear,
it is impossible to use saucevr pls fix.

**Comment by cspark-development** [comment]
Can confirm this has just started happening every execution after the 28th February

**Comment by sasgor2005** [comment]
roblox got an new body system rework included diffrent coding. basically roblox fixed all FE scripts what exists included this one

**Comment by dsfrgr** [comment]
any chance of updating this? or is it just dead

**Comment by sanderabelsen** [comment]
its  dead

**Comment by sanderabelsen** [comment]
hope it gets fixed soon
